### ISSUE TITLE
可以加上统计本月的电费用量、本月已用电费、获取余额增加定时任务6-24点每过一小时获取一次

### ISSUE THREAD

**Issue by 907739769** [renhaiidea/sgcc_electricity#4]
可以加上
1.统计本月的电费用量、本月已用电费
2.获取余额增加定时任务6-24点每过一小时获取一次

**Comment by fatwang2000** [comment]
统计本月电费可以有，但计费方式可能各地区有不同方式，不建议计算本月已用电费。
余额变化可以适当增加获取频率。

**Comment by renhaiidea** [comment]
统计每月电费可以去homeassistant实现，增加余额变化的频率只需要修改main.py中的40行[schedule.every().day.at(JOB_START_TIME).do(run_task, fetcher, updator)](https://github.com/renhaiidea/sgcc_electricity/blob/b20164e1165ee9c6b33e913adf41a74ccf858775/scripts/main.py#L40C1-L40C1)修改为
`schedule.every(HOURS).hours.do(run_task, fetcher, updator) # 修改HOURS的值，例如HOURS=8将每隔8小时执行一次，不过建议不要太频繁 `。
然后注释掉42-48行的代码就行了。

可以克隆仓库了自行build。

**Comment by 645340633** [comment]
是需要自己重新编译吗？这样就劝退小白了。

**Comment by renhai-lab** [comment]
> 是需要自己重新编译吗？这样就劝退小白了。

是的，很简单的，你按照[手动部署方法](https://github.com/renhai-lab/sgcc_electricity#2%E6%96%B9%E6%B3%95%E4%BA%8C%E6%9C%AC%E5%9C%B0%E8%87%AA%E8%A1%8C%E6%9E%84%E5%BB%BA%E5%AE%B9%E5%99%A8)试试

**Comment by 645340633** [comment]
我用的是hassio，可以手动部署吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月16日(周一) 上午9:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [renhai-lab/sgcc_electricity] 可以加上统计本月的电费用量、本月已用电费、获取余额增加定时任务6-24点每过一小时获取一次 (Issue #4)




  
是需要自己重新编译吗？这样就劝退小白了。
  
是的，很简单的，你按照手动部署方法试试
