### ISSUE TITLE
配置了数据库存储,但是日用电量在ha里只能看到一天的数据

### ISSUE THREAD

**Issue by zhouchang714** [renhaiidea/sgcc_electricity#5]
env配置如下
![image](https://github.com/renhaiidea/sgcc_electricity/assets/24220559/75a23ff4-256e-425c-88f5-372c92a6aafa)
此外,注意到mongo中数据集合与户号对应不上,如图只有户号为4013结尾的集合有数据,但是这些数据户号为应该为6028,其他集合均无数据
![image](https://github.com/renhaiidea/sgcc_electricity/assets/24220559/4badf2a4-17bb-4b98-a315-00b6ff9411d8)
在ha中数据,每个户号下的昨日用电都只有一天的数据,没有历史数据

**Comment by renhaiidea** [comment]
1. 据我了解，昨日用电量实体类型属于sensor，每次更新只会保留一次数据，所以随着程序运行此sendor可以反应出每日电量的变化。你可以试试在homeassistant进行借助node-red进行历史数据库的查询，然后进行数据展示。
2. 多户号中mongo中数据集合与户号对应不上属于bug，会在下此发布修复。
