### ISSUE TITLE
我怎么可以在群晖的docker里面运行

### ISSUE THREAD

**Issue by Warm-rain** [renhaiidea/sgcc_electricity#7]
我已经正常拉取最新镜像并启动了，可是他并没有任何放映，资源占用几乎没有，占用你宝贵的时间指点一下
![屏幕截图 2023-08-09 223423.png](https://s2.loli.net/2023/08/09/PyhLNfv8CcWxSeZ.png)
![屏幕截图 2023-08-09 223623.png](https://s2.loli.net/2023/08/09/yMCbdagmuwA3vf4.png)
![屏幕截图 2023-08-09 223519.png](https://s2.loli.net/2023/08/09/ythDR3iKFQloJPp.png)
![屏幕截图 2023-08-09 223257.png](https://s2.loli.net/2023/08/09/JIqSRkY1NU58sMo.png)
![屏幕截图 2023-08-09 223532.png](https://s2.loli.net/2023/08/09/mueMkPyWG15Bn7X.png)

**Comment by renhaiidea** [comment]
虽然但是，我没有用过群辉设备，百度或者问问chatgpt一下？

**Comment by Warm-rain** [comment]
![屏幕截图 2023-08-10 123313.png](https://s2.loli.net/2023/08/10/DjNfrCcOT2JdR3g.png)

总于在群晖里面正常运行了

**Comment by leopoldaa** [comment]
麻烦可以讲讲群辉的操作方式吗，我的你前边报错的截面一样

**Comment by Warm-rain** [comment]
@leopoldaa 过太久了具体细节记不清了，是通过命令行构建成功安装的。
